<a href="https://colab.research.google.com/github/Ravi-Poddar26/missing-values/blob/master/H_M_V(7).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# KNN Imputer
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
d = sns.load_dataset('titanic')
df = d[['age', 'pclass', 'fare', 'survived']]

In [ ]:
df.head()

    age  pclass     fare  survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [ ]:
df.isnull().mean()*100

age         19.86532
pclass       0.00000
fare         0.00000
survived     0.00000
dtype: float64

In [ ]:
X = df.drop(columns=['survived'])
y = df['survived']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [ ]:
X_train.head()

      age  pclass     fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [ ]:
knn = KNNImputer(n_n)

In [ ]:
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [ ]:
pd.DataFrame(X_train_trf, columns=X_train.columns)

      age  pclass      fare
0    40.0     1.0   27.7208
1     4.0     3.0   16.7000
2    47.0     3.0    9.0000
3     9.0     3.0   31.3875
4    20.0     3.0    9.8458
..    ...     ...       ...
707  30.0     3.0    8.6625
708  24.2     3.0    8.7125
709  71.0     1.0   49.5042
710  28.0     1.0  221.7792
711  42.8     1.0   25.9250

[712 rows x 3 columns]

In [ ]:
lr = LogisticRegression()
lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)
accuracy_score(y_test, y_pred)

0.7039106145251397

In [ ]:
# comparison with simple imputer --- mean

si

NameError: name 'si' is not defined